In [105]:
%%html
<style>
div.text_cell_render.rendered_html {
overflow-x: hidden !important;
}
code {
    max-height: unset !important;
}
body.rise-enabled div.inner_cell>div.input_area {
    font-size: 150%;
}

body.rise-enabled div.output_subarea.output_text.output_result {
    font-size: 150%;
}
body.rise-enabled div.output_subarea.output_text.output_error {
    font-size: 150%;
}

body.rise-enabled div.output_subarea.output_text.output_stream.output_stdout {
  font-size: 150%;
}

div.prompt {display:none}
</style>


## The Shell

  * The shell is a text-based program that allows the user to perform 
        - file operations (move, copy, delete)
        - execute programs

  * In graphical desktop environments a **terminal** application is used
    to manage text input and output.
    The terminal talks to the shell program.'

  * Most commonly used shell under Linux/macOS is **bash**. Further shells
    are e.g. `zsh` und `fish`.

  * On Windows the **command prompt** (`command.com`) is a rudimentary
    shell. `Powershell` is a common alternative.

## Directories (a.k.a. Folders)

  * On Linux/macOS/Android/iOS, each file has an unique **path**
    of the form

    ```bash
    /Directory1/Directory2/.../DirectoryN/FileName
    ```

  * Filenames are case sensitive:
  
    ```bash
    /foo  !=   /Foo
    ```

  * The directory `/` is called the **root directory**.

  * To show the files in directory `<path>`, use shell command

    ```bash
    ls <path> 
    ```

## Current Working Directory

  * The shell always has a **current working directory (cwd)** that can be shown using

    ```bash
    pwd     # "print working directory"
    ```

  * To show files in the cwd, use

    ```bash
    ls
    ```

  * To change the cwd, use

    ```bash
    cd <path>   # "change directory"
    ```

  * Each Linux/macOS user has a **home directory**. To go there use:

    ```bash
    cd
    ```

## Relative Paths

  * Paths of the form
    
    ```bash
    Directory1/Directory2/.../DirectoryN/FileName
    ```

    are relative to the current working directory. E.g., for the current working directory

    ```bash
    /a/b/c
    ```

    the path

    ```bash
    d/e/f
    ```

    is equivalent to

    ```bash
    /a/b/c/d/e/f
    ```

  * Relative paths can be used everywhere where a path is expected, e.g.
    `cd` or `ls`.

## Important Commands

```bash
cd <path>            # change CWS to <path>

ls <path>            # list files in <path>
ls -a <path>         # also list files starting with '.'
ls -l <path>         # show additional information

mkdir <path>         # create directory <path>
cp <pathA> <pathB>   # copy file <pathA> to <pathB>
mv <pathA> <pathB>   # move file from <pathA> to <pathB>

rm <path>            # delete file <path> (no 'recycling bin')
rmdir <path>         # delete empty directory <path>
rm -r <path>         # recursively delete directory <path> 
                     # with all subdirectories
                     
cat <path>           # show content of file <path>
less <path>          # interactively show content of file <path>
                     # quit with 'q'
man <command>        # show manual page for <command>
```

## Launching Programs

  * Installed programs have a path in the filesystem, using which they can be executed. E.g.

    ```bash
    /usr/bin/kate <path>
    ```

    opens the file `<path>` with the editor `kate`. 

  * Some directories, e.g. `/usr/bin` are always searched for executable program
    (controlled by the `$PATH` variable).
    Thus, we can also write

    ```bash
    kate <path>
    ```

## Why bother?

  * Shell commands are easier to describe than the usage of a GUI.

  * Standardized (POSIX-Standard).

  * Programmable.

  * Complex tasks easier than with graphical file managers.

  * It's easer to write a terminal-based program than a GUI program.

## Hello World

1. Save this script to a file `hello.py`

2. Run the script by executing
  ```shell
  python3 hello.py
  ```

3. Make the script executable and run it:
  ```shell
  chmod u+x hello.py
  ./hello.py
  ```

4. What happens if you replace `str(length)` by `length`

In [ ]:
#!/bin/bash
name = input('Your name? ')
length = len(name)
if length == 0:
    name = 'Nameless'

print('Hello, ' + name + '!')
print('Your name is ' + str(length)
      + ' characters long.')

## A loop

 1. Execute the following script
 
 2. Compute the same sum by counting backwards
 
 3. Compute the sum of the first $n$ square numbers.

In [ ]:
n = int(input('n = '))
i = 1
s = 0
while i < n + 1:
    s = s + i
    i = i + 1
print('The sum of the first', n,
      'natural numbers is', s)

## Branching

1. Execute the following script.

2. Replace `elif` by `else` and `if`

In [ ]:
i = 1
while i < 100 + 1:
    if i % (3 * 5) == 0:
        print('FizzBuzz', end=',')
    elif i % 3 == 0:
        print('Fizz', end=',')
    elif i % 5 == 0:
        print('Buzz', end=',')
    else:
        print(i, end=',')
    i = i + 1

## Lists

1. Execute the following script.

2. The first index is **0**.
 
3. Use negative indices to refer to the last elements of the list.

4. Lists can be sliced as follows:
   ```python
   l[start:stop:step]
   ```
   **Slices are half-open intervals.**
   
   Print the last 5 Fibonacci numbers in reversed order.

In [ ]:
fibs = [1, 1]
i = 2
while i < 10:
    fibs.append(fibs[i-2] + fibs[i-1])
    i = i + 1
print(fibs)

## for Loops

* Use
  ```python
  for <name> in <iterable>:
      <block>
  ```
  to loop over the element of any given iterable 
  (e.g. a list).

In [ ]:
l = [4, 6, 3, 2]
prod = 1
for x in l:
    prod = prod * x
print(prod)

## Ranges

* To create a simple counting loop, use the
  ```python
  range(start, stop, step)
  ```
  iterable.

In [ ]:
l = [5, 2, 4, 3, 2]
print(l)
for i in range(len(l)):
    for j in range(len(l) - 1):
        if l[j] > l[j+1]:
            x = l[j]
            l[j] = l[j+1]
            l[j+1] = x
    print(l)

## Functions

What happens without the `return` statement?

In [ ]:
def binom(n, k):
    fn = fac(n)
    fk = fac(k)
    fnk = fac(n-k)
    c = fn // (fk * fnk)
    return c
    
def fac(n):
    val = 1
    for k in range(1, n+1):
        val = val * k
    return val

n = int(input('n = '))
k = int(input('k = '))
assert n >= k, 'n has to be larger than k!'
print(binom(n, k))

## Local and global names

1. What happens when the following code is executed?

2. What happens, when the first line of `f` is uncommented?

3. What happens, when the second line of `f` is uncommented?

4. What happens, when the last line of `f` is uncommented?

5. What happens, when the second and last lines of `f` are uncommented?

In [ ]:
def f():
    # x = 1
    # global x
    print(x)
    # x = 100

x = 99
f()
print(x)

**RULE:** A name is local, when it is a function argument or when it is the target of an assignment in the function body (and when it is not marked as `global`).


## Functions are objects

* Functions are values that can be passed like any other value
* With `lambda` expressions, functions can be created on-the-fly

In [ ]:
def integral(f, a, b, n):
    h = (b - a) / n
    result = 0.
    for i in range(n):
        result = result + f(a + 0.5*h + i*h) * h
    return result

def f1(x):
    return x*3

print(integral(f1, 0., 1., 10))
print(integral(lambda x:x**2, 0., 1., 100))

## Extension modules

* Extension modules need to be `import`ed before being available in the script.
* The [standard library](https://docs.python.org/3/library/index.html) modules are always available.
* Third-party modules are usually hosted on [PyPI](https://pypi.org)

In [ ]:
import time
from random import uniform
import math as m

N = 10000
tic = time.time()
hits = 0
for i in range(N):
    x = uniform(-1, 1)
    y = uniform(-1, 1)
    if x**2 + y**2 < 1:
        hits = hits + 1

pi_approx = 4 * (hits / N)
print('error:', pi_approx - m.pi,
      '\nduration:', time.time() - tic)

## NumPy

* In Python, there is no builtin array/matrix data type.

* The `numpy` module provides a `ndarray` class which similar performance characteristics as MATLAB matrices.

* Vectors are usually represented as 1d-arrays. (No difference between row and column vectors.)

In [ ]:
import numpy as np
v = np.array([1, 2, 3])

A = np.array([[1, 2, 3],
              [4, 5, 6]])

print(v.ndim, A.ndim)
print(v.shape, A.shape)
print(len(A))

## Special arrays

In [ ]:
np.zeros((2, 3))

In [ ]:
np.ones((2,2))

In [ ]:
np.eye(3)

In [ ]:
np.arange(4)

In [ ]:
np.full(4, 5)

In [ ]:
np.random.normal(size=3)

## Basic Operations

In [ ]:
A = np.array([[1,2],[3,4]])
B = np.array([[5,6],[7,8]])
print(A, B, sep='\n')

In [ ]:
A + B

In [ ]:
A * B

In [ ]:
np.sin(A)

In [ ]:
A.dot(B)

In [ ]:
A @ B

In [ ]:
np.min(A)

In [ ]:
np.min(A, axis=0)

In [ ]:
np.linalg.norm(A, axis=1)

## Slicing

In [ ]:
A = np.array([[1,2,3],[4,5,6],[7,8,9]])
A

In [ ]:
A[0, 0]

In [ ]:
A[1, -1]

In [ ]:
A[1:, :]

In [ ]:
A[:, 1:2]

In [ ]:
A[:2, :2]

In [35]:
A[:, 1]

array([2, 5, 8])

In [37]:
A[0]

array([1, 2, 3])

In [39]:
for x in A:
    print('*', x, '*')

* [1 2 3] *
* [4 5 6] *
* [7 8 9] *


## Broadcasting and item assignment

In [47]:
A = np.array([[1,2,3],[4,5,6],[7,8,9]])
B = np.arange(90, 93)
A, B

(array([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]), array([90, 91, 92]))

In [48]:
A + B

array([[ 91,  93,  95],
       [ 94,  96,  98],
       [ 97,  99, 101]])

In [49]:
A + 10

array([[11, 12, 13],
       [14, 15, 16],
       [17, 18, 19]])

In [50]:
A[0, 0] = 7
A

array([[7, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [51]:
A[0, 1:] = A[1, 1:]
A

array([[7, 5, 6],
       [4, 5, 6],
       [7, 8, 9]])

In [53]:
A[:, 1:] = 9
A

array([[7, 9, 9],
       [4, 9, 9],
       [7, 9, 9]])

In [54]:
A[:] = 0
A

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

## Views and copies

* Slicing and indexing create view arrays. Modifying a view also modifies the original array.
* Copies are created using the `copy` method.
* Some methods create views, some copies!
* Advanced indexing (by a list of indices) always creates copies!

In [61]:
A = np.array([[1, 2, 3],
              [4, 5, 6]])
B = A[1, 1:]
B[:] = 0
A, B.base is A

(array([[1, 2, 3],
        [4, 0, 0]]), True)

In [60]:
A = np.array([[1, 2, 3],
              [4, 5, 6]])
B = A[1]
B[:] = 0
A, B.base is A

(array([[1, 2, 3],
        [0, 0, 0]]), True)

In [62]:
A = np.array([[1, 2, 3],
              [4, 5, 6]])
B = A[1, 1:].copy()
B[:] = 0
A, B.base is A

(array([[1, 2, 3],
        [4, 5, 6]]), False)

In [63]:
A = np.array([[1, 2, 3],
              [4, 5, 6]])
B = A[1, [1,2]]
B[:] = 0
A, B.base is A

(array([[1, 2, 3],
        [4, 5, 6]]), False)

## dtype

In [64]:
np.zeros(42).dtype

dtype('float64')

In [65]:
np.ones(42).dtype

dtype('float64')

In [66]:
np.eye(42).dtype

dtype('float64')

In [67]:
np.arange(42).dtype

dtype('int64')

In [68]:
np.array([1,2,3]).dtype

dtype('int64')

In [69]:
np.array([1.,2,3]).dtype

dtype('float64')

In [70]:
np.array([1, 2, 3]) / 3

array([0.33333333, 0.66666667, 1.        ])

In [79]:
np.array([1, [1,2], 3]).dtype

dtype('O')

## Array constructions

In [81]:
np.hstack([np.arange(3), np.ones(3)])

array([0., 1., 2., 1., 1., 1.])

In [82]:
np.vstack([np.arange(3), np.ones(3)])

array([[0., 1., 2.],
       [1., 1., 1.]])

In [99]:
A = np.arange(6)
B = A.reshape((2, 3))
B, B.base is A

(array([[0, 1, 2],
        [3, 4, 5]]), True)

In [100]:
A = np.arange(6)
B = A.ravel()
B, B.base is A


(array([0, 1, 2, 3, 4, 5]), True)

In [95]:
A = np.eye(4)[::2, :]
B = A.ravel()
B.base is A

False

* `ravel` and `reshape` only create copies when necessary!

## Comparisons

In [101]:
v = np.array([1, 2, 3, 4])
w = np.array([1, 2, 5, 4])
v == w

array([ True,  True, False,  True])

In [102]:
if v == w:
    print('equal!')

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [103]:
if np.any(v == w):
    print('some equal!')

some equal


In [104]:
if np.all(v == w):
    print('all equal!')